"""DuckDB source-reader adapter over an indexed Smritikosh database."""

from __future__ import annotations

import json
import re
from dataclasses import replace
from pathlib import Path
from typing import TYPE_CHECKING, Final

import duckdb

from smritikosh.models import (
    IndexedChunk,
    IndexInfo,
    OutlineEntry,
    SearchOptions,
    SearchResult,
    SourceLine,
    TextMatch,
)
from smritikosh.ports.embedder import EmbeddingIdentity
from smritikosh.ports.source_reader import SourceReader

if TYPE_CHECKING:
    from smritikosh.ports.embedder import Embedder

__all__ = [
    "DuckDBSourceReader",
    "IndexInfo",
    "IndexedChunk",
    "OutlineEntry",
    "SearchOptions",
    "SourceLine",
    "TextMatch",
]

_NON_PRODUCTION_PATH_PENALTY: Final[float] = 0.8

#: A hit is dropped when a better-scoring hit already covers this much of it.
#: Half is deliberately permissive: the overlaps worth removing are windows of
#: one definition, which repeat far more than half of each other, while two
#: genuinely different definitions in one file share no lines at all.
_OVERLAP_DROP_FRACTION: Final[float] = 0.5

#: Candidates fetched per requested result, so that dropping repeats still
#: leaves a full page of answers.
_OVERFETCH: Final[int] = 3
_TEST_INTENT_PATTERN: Final[re.Pattern[str]] = re.compile(
    r"(?<!\w)(?:tests?|testing|pytest|unittest|specs?)(?!\w)",
    re.IGNORECASE,
)
_DOCUMENTATION_INTENT_PATTERN: Final[re.Pattern[str]] = re.compile(
    r"(?<!\w)(?:docs?|documentation|readme|markdown|changelog)(?!\w)",
    re.IGNORECASE,
)
_TEST_PATH_SQL: Final[str] = """
    regexp_matches(lower(path), '(^|/)(tests?|__tests__|specs?)(/|$)')
    OR regexp_matches(
        lower(path),
        '(^|/)(test_[^/]*|[^/]*_(test|spec)|'
        || '[^/]*\\.(test|spec))\\.[^/]+$'
    )
"""
_DOCUMENTATION_PATH_SQL: Final[str] = """
    regexp_matches(lower(path), '(^|/)(docs?|documentation)(/|$)')
    OR regexp_matches(lower(path), '(^|/)(readme|changelog)(\\.[^/]*)?$')
    OR regexp_matches(lower(path), '\\.(md|mdx|rst|adoc)$')
"""


class DuckDBSourceReader(SourceReader):
    """Explore one Smritikosh index without acquiring a write connection."""

    def __init__(self, db_path: str) -> None:
        """Open an existing index in read-only mode.

        Args:
            db_path: Path to the Smritikosh DuckDB file.
        """
        if not Path(db_path).is_file():
            raise FileNotFoundError(f"Smritikosh index not found: {db_path}")
        self._connection = duckdb.connect(database=db_path, read_only=True)

    def close(self) -> None:
        """Close the read-only database connection."""
        self._connection.close()

    def index_info(self) -> IndexInfo:
        """Return index counts and embedding dimensions."""
        counts: dict[str, int] = dict(
            self._connection.execute(
                "SELECT kind, count(*) FROM nodes GROUP BY kind"
            ).fetchall()
        )
        vector_count: int = self._connection.execute(
            "SELECT count(*) FROM vectors"
        ).fetchone()[0]
        dimensions_row: tuple[str] | None = self._connection.execute(
            "SELECT value FROM kv_store WHERE key = 'embedder_dims'"
        ).fetchone()
        dimensions: int | None = (
            int(dimensions_row[0]) if dimensions_row is not None else None
        )
        return IndexInfo(
            files=counts.get("file", 0),
            chunks=counts.get("chunk", 0),
            vectors=vector_count,
            dimensions=dimensions,
        )

    def embedding_identity(self) -> EmbeddingIdentity | None:
        """Return the vector-space identity stored with this index."""
        row: tuple[str] | None = self._connection.execute(
            "SELECT value FROM kv_store WHERE key = 'embedding_identity'"
        ).fetchone()
        return EmbeddingIdentity(**json.loads(row[0])) if row else None

    def semantic_search(
        self,
        queries: list[str],
        *,
        embedder: Embedder,
        options: SearchOptions | None = None,
    ) -> list[SearchResult]:
        """Search for chunks using one or more natural-language queries.

        Args:
            queries: Ad hoc semantic queries generated by the caller.
            embedder: Query embedder matching the indexed vectors.
            options: Search count and optional path filters.

        Returns:
            Deduplicated results ranked by their best score across all queries.

        Raises:
            ValueError: If no query is supplied or ``top_k`` is not positive.
            RuntimeError: If the database has no vector index.
        """
        normalized_queries: list[str] = [
            query.strip() for query in queries if query.strip()
        ]
        if not normalized_queries:
            raise ValueError("At least one non-empty query is required")
        options = options or SearchOptions()
        if options.top_k <= 0:
            raise ValueError("top_k must be positive")

        dimensions: int | None = self.index_info().dimensions
        if dimensions is None:
            raise RuntimeError("No vector index found")
        if embedder.dims != dimensions:
            raise RuntimeError(
                f"Embedder dimensions {embedder.dims} do not match index "
                f"dimensions {dimensions}"
            )

        vectors: list[list[float]] = embedder.encode_queries(normalized_queries)
        hits: dict[str, tuple[float, IndexedChunk]] = {}
        for query, vector in zip(normalized_queries, vectors, strict=True):
            for score, chunk in self._search_vector(
                vector=vector,
                dimensions=dimensions,
                options=options,
                test_path_penalty=self._path_penalty(
                    query,
                    intent_pattern=_TEST_INTENT_PATTERN,
                ),
                documentation_path_penalty=self._path_penalty(
                    query,
                    intent_pattern=_DOCUMENTATION_INTENT_PATTERN,
                ),
            ):
                previous: tuple[float, IndexedChunk] | None = hits.get(chunk.chunk_id)
                if previous is None or score > previous[0]:
                    hits[chunk.chunk_id] = (score, chunk)

        ranked: list[tuple[float, IndexedChunk]] = self._drop_repeats(
            sorted(hits.values(), key=lambda hit: hit[0], reverse=True)
        )
        return [
            SearchResult(
                path=chunk.path,
                start_line=chunk.start_line,
                end_line=chunk.end_line,
                snippet=chunk.text,
                score=score,
                chunk_kind=chunk.chunk_kind,
                symbol=chunk.symbol,
                chunk_id=chunk.chunk_id,
            )
            for score, chunk in ranked[: options.top_k]
        ]

    def find_paths(self, pattern: str, *, limit: int = 50) -> list[str]:
        """Find indexed paths containing a case-insensitive substring.

        Args:
            pattern: Substring to find in indexed paths.
            limit: Maximum number of paths to return.

        Returns:
            Matching paths in lexical order.
        """
        self._validate_limit(limit)
        rows: list[tuple[str]] = self._connection.execute(
            """
            SELECT DISTINCT path
            FROM nodes
            WHERE path IS NOT NULL AND contains(lower(path), lower(?))
            ORDER BY path
            LIMIT ?
            """,
            [pattern, limit],
        ).fetchall()
        return [row[0] for row in rows]

    def text_search(
        self,
        text: str,
        *,
        path: str | None = None,
        limit: int = 20,
    ) -> list[IndexedChunk]:
        """Find chunks containing exact text, case-insensitively.

        Args:
            text: Text or symbol name to locate.
            path: Optional exact indexed path.
            limit: Maximum number of chunks to return.

        Returns:
            Matching chunks ordered by path and source line.
        """
        self._validate_limit(limit)
        path_clause: str = " AND path = ?" if path is not None else ""
        parameters: list[str | int] = [text]
        if path is not None:
            parameters.append(path)
        parameters.append(limit)
        rows: list[tuple[str, str | None, str, str]] = self._connection.execute(
            f"""
            SELECT id, name, path, metadata
            FROM nodes
            WHERE kind = 'chunk'
              AND contains(lower(json_extract_string(metadata, '$.text')), lower(?))
              {path_clause}
            ORDER BY path, CAST(json_extract(metadata, '$.start_line') AS INTEGER)
            LIMIT ?
            """,  # noqa: S608
            parameters,
        ).fetchall()
        return [self._to_chunk(row) for row in rows]

    def find_text_lines(
        self,
        text: str,
        *,
        path: str | None = None,
        limit: int = 20,
    ) -> list[TextMatch]:
        """Find the individual source lines containing exact text.

        Args:
            text: Text or symbol name to locate.
            path: Optional exact indexed path.
            limit: Maximum number of matching lines to return.

        Returns:
            Matching lines ordered by path and source line, each returned once
            however many overlapping chunks stored it.
        """
        self._validate_limit(limit)
        needle: str = text.lower()
        matches: dict[tuple[str, int, str], TextMatch] = {}
        for chunk in self.text_search(text, path=path, limit=limit):
            chunk_lines: list[str] = chunk.text.split("\n")
            # A grouped chunk concatenates definitions that are not adjacent in
            # the file, so its text does not line up with the lines it claims.
            # Its start line is then the closest honest anchor available.
            aligned: bool = len(chunk_lines) == chunk.end_line - chunk.start_line + 1
            for offset, line in enumerate(chunk_lines):
                if needle not in line.lower():
                    continue
                number: int = chunk.start_line + offset if aligned else chunk.start_line
                match = TextMatch(
                    path=chunk.path,
                    line_number=number,
                    text=line.strip(),
                    exact_line=aligned,
                )
                matches.setdefault((match.path, match.line_number, match.text), match)
        ordered: list[TextMatch] = sorted(
            matches.values(), key=lambda match: (match.path, match.line_number)
        )
        return ordered[:limit]

    def get_chunks(
        self,
        path: str,
        *,
        start_line: int | None = None,
        end_line: int | None = None,
    ) -> list[IndexedChunk]:
        """Return chunks from one indexed path, optionally overlapping a line range.

        Args:
            path: Exact indexed source path.
            start_line: Optional first line of the desired range.
            end_line: Optional last line of the desired range.

        Returns:
            Chunks ordered by their starting line.

        Raises:
            ValueError: If a supplied line number is not positive or the range
                is reversed.
        """
        self._validate_line_range(start_line=start_line, end_line=end_line)
        clauses: list[str] = ["kind = 'chunk'", "path = ?"]
        parameters: list[str | int] = [path]
        if start_line is not None:
            clauses.append("CAST(json_extract(metadata, '$.end_line') AS INTEGER) >= ?")
            parameters.append(start_line)
        if end_line is not None:
            clauses.append(
                "CAST(json_extract(metadata, '$.start_line') AS INTEGER) <= ?"
            )
            parameters.append(end_line)
        where_clause: str = " AND ".join(clauses)
        rows: list[tuple[str, str | None, str, str]] = self._connection.execute(
            f"""
            SELECT id, name, path, metadata
            FROM nodes
            WHERE {where_clause}
            ORDER BY CAST(json_extract(metadata, '$.start_line') AS INTEGER)
            """,  # noqa: S608
            parameters,
        ).fetchall()
        return [self._to_chunk(row) for row in rows]

    def get_chunks_by_ids(self, chunk_ids: list[str]) -> dict[str, IndexedChunk]:
        """Look up indexed chunks by id, keyed by the id that found them.

        An id with no stored chunk is absent from the mapping.  Returning a
        list would have made that miss invisible: a ranked caller zipping
        scores against a silently shorter result mis-pairs every entry after
        the gap.  Ordering is the caller's — it already holds the ranking.
        """
        if not chunk_ids:
            return {}
        placeholders = ", ".join("?" for _ in chunk_ids)
        rows: list[tuple[str, str | None, str, str]] = self._connection.execute(
            f"""
            SELECT id, name, path, metadata
            FROM nodes
            WHERE kind = 'chunk' AND id IN ({placeholders})
            """,  # noqa: S608
            chunk_ids,
        ).fetchall()
        return {row[0]: self._to_chunk(row) for row in rows}

    def get_outline(self, path: str) -> list[OutlineEntry]:
        """List what one indexed path defines, without any of its source.

        An oversized definition is stored as several windows; they share a
        symbol, so consecutive windows of one definition collapse back into
        the single entry the reader expects.

        Args:
            path: Exact indexed source path.

        Returns:
            One entry per definition, in source order.
        """
        entries: list[OutlineEntry] = []
        for chunk in self.get_chunks(path):
            previous: OutlineEntry | None = entries[-1] if entries else None
            same_definition: bool = (
                previous is not None
                and chunk.symbol is not None
                and previous.symbol == chunk.symbol
                and previous.chunk_kind == chunk.chunk_kind
            )
            if same_definition and previous is not None:
                entries[-1] = replace(
                    previous, end_line=max(previous.end_line, chunk.end_line)
                )
                continue
            entries.append(
                OutlineEntry(
                    symbol=chunk.symbol,
                    chunk_kind=chunk.chunk_kind,
                    start_line=chunk.start_line,
                    end_line=chunk.end_line,
                )
            )
        return entries

    def get_source_lines(
        self,
        path: str,
        *,
        start_line: int | None = None,
        end_line: int | None = None,
    ) -> list[SourceLine]:
        """Rebuild the source of one path from its chunks, line by line.

        Chunks overlap, so the same source line is stored several times over.
        Merging them by line number returns each line once, in source order,
        instead of the repeated windows ``get_chunks`` yields.

        A chunk whose text does not span exactly the lines it claims — a
        grouped chunk concatenates definitions that are not adjacent in the
        file — cannot be mapped back onto line numbers and is skipped, so the
        rebuilt range can have gaps.

        Args:
            path: Exact indexed source path.
            start_line: Optional first line of the desired range.
            end_line: Optional last line of the desired range.

        Returns:
            Distinct source lines in ascending line order.

        Raises:
            ValueError: If a supplied line number is not positive or the range
                is reversed.
        """
        chunks: list[IndexedChunk] = self.get_chunks(
            path,
            start_line=start_line,
            end_line=end_line,
        )
        lines: dict[int, str] = {}
        for chunk in chunks:
            chunk_lines: list[str] = chunk.text.split("\n")
            if len(chunk_lines) != chunk.end_line - chunk.start_line + 1:
                continue
            for offset, text in enumerate(chunk_lines):
                number: int = chunk.start_line + offset
                if start_line is not None and number < start_line:
                    continue
                if end_line is not None and number > end_line:
                    continue
                lines[number] = text
        return [
            SourceLine(line_number=number, text=lines[number])
            for number in sorted(lines)
        ]

    def _search_vector(
        self,
        *,
        vector: list[float],
        dimensions: int,
        options: SearchOptions,
        test_path_penalty: float,
        documentation_path_penalty: float,
    ) -> list[tuple[float, IndexedChunk]]:
        clauses: list[str] = ["n.kind = 'chunk'"]
        parameters: list[object] = [vector]
        if options.include_paths:
            include_clause: str = " OR ".join(
                "n.path LIKE ?" for _ in options.include_paths
            )
            clauses.append(f"({include_clause})")
            parameters.extend(options.include_paths)
        for pattern in options.exclude_paths:
            clauses.append("n.path NOT LIKE ?")
            parameters.append(pattern)
        parameters.extend([test_path_penalty, documentation_path_penalty])
        parameters.append(options.top_k * _OVERFETCH)
        where_clause: str = " AND ".join(clauses)
        rows: list[tuple[str, str | None, str, str, float]] = self._connection.execute(
            self._vector_search_sql(
                dimensions=dimensions,
                where_clause=where_clause,
            ),
            parameters,
        ).fetchall()
        return [(row[4], self._to_chunk(row[:4])) for row in rows]

    @staticmethod
    def _drop_repeats(
        ranked: list[tuple[float, IndexedChunk]],
    ) -> list[tuple[float, IndexedChunk]]:
        """Remove hits that mostly repeat the lines of a better-scoring hit.

        Chunks overlap by design — a class chunk contains its methods, and an
        oversized definition is stored as overlapping windows — so one region
        of one file can fill a result page several times over.

        The test is what fraction of the candidate's own lines a kept hit
        already covers, not whether one contains the other: sibling windows
        share a seam without either containing the other, which is why
        containment never fires on them.
        """
        kept: list[tuple[float, IndexedChunk]] = []
        for score, chunk in ranked:
            span: int = chunk.end_line - chunk.start_line + 1
            repeats: bool = any(
                other.path == chunk.path
                and (
                    max(
                        0,
                        min(other.end_line, chunk.end_line)
                        - max(other.start_line, chunk.start_line)
                        + 1,
                    )
                    / span
                )
                >= _OVERLAP_DROP_FRACTION
                for _, other in kept
            )
            if not repeats:
                kept.append((score, chunk))
        return kept

    @staticmethod
    def _path_penalty(query: str, *, intent_pattern: re.Pattern[str]) -> float:
        """Return full weight when a query explicitly requests a path category."""
        if intent_pattern.search(query):
            return 1.0
        return _NON_PRODUCTION_PATH_PENALTY

    @staticmethod
    def _vector_search_sql(*, dimensions: int, where_clause: str) -> str:
        """Build the vector query with production-first score adjustments."""
        return f"""
            WITH candidates AS (
                SELECT n.id, n.name, n.path, n.metadata,
                       array_cosine_similarity(
                           v.vector, ?::FLOAT[{dimensions}]
                       ) AS raw_score
                FROM vectors AS v
                JOIN nodes AS n ON n.id = v.chunk_id
                WHERE {where_clause}
            )
            SELECT id, name, path, metadata,
                   CASE
                       WHEN ({_TEST_PATH_SQL})
                       THEN raw_score - ((1.0 - ?) * abs(raw_score))
                       WHEN ({_DOCUMENTATION_PATH_SQL})
                       THEN raw_score - ((1.0 - ?) * abs(raw_score))
                       ELSE raw_score
                   END AS score
            FROM candidates
            ORDER BY score DESC
            LIMIT ?
        """  # noqa: S608

    @staticmethod
    def _to_chunk(row: tuple[str, str | None, str, str]) -> IndexedChunk:
        """Build a chunk from an ``(id, name, path, metadata)`` row."""
        metadata: dict[str, object] = json.loads(row[3])
        return IndexedChunk(
            chunk_id=row[0],
            symbol=row[1],
            path=row[2],
            start_line=int(metadata["start_line"]),
            end_line=int(metadata["end_line"]),
            text=str(metadata["text"]),
            chunk_kind=(
                str(metadata["chunk_kind"])
                if metadata.get("chunk_kind") is not None
                else None
            ),
        )

    @staticmethod
    def _validate_limit(limit: int) -> None:
        if limit <= 0:
            raise ValueError("limit must be positive")

    @staticmethod
    def _validate_line_range(
        *,
        start_line: int | None,
        end_line: int | None,
    ) -> None:
        if start_line is not None and start_line <= 0:
            raise ValueError("start_line must be positive")
        if end_line is not None and end_line <= 0:
            raise ValueError("end_line must be positive")
        if start_line is not None and end_line is not None and start_line > end_line:
            raise ValueError("start_line cannot be greater than end_line")
